	--> autostart.lua

hl.on("hyprland.start", function()
	hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && systemctl --user start graphical-session.target")
        hl.exec_cmd("systemctl --user set-environment WAYLAND_DISPLAY=wayland-1 XDG_CURRENT_DESKTOP=Hyprland && systemctl --user start hyprland-session.service")
        hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("nm-applet &")
	hl.exec_cmd("waybar & awww-daemon & sleep 1 && awww img ~/.config/hypr/current_wallpaper --transition-type none")
	hl.exec_cmd("wl-paste --watch cliphist store &")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("swaync")
	hl.exec_cmd("swayosd-server >/dev/null 2>&1")
	hl.exec_cmd("hypridle")
	hl.exec_cmd('sh -c "mpc idleloop player | while read; do ~/.config/scripts/mpd-notify.sh; done"')
	hl.exec_cmd("mpd-mpris &")
	hl.exec_cmd("numlockx on")
	hl.exec_cmd("qs -c overview")

	--> launch apps into specific workspaces (silent)
	-- hl.exec_cmd("[workspace special:term silent] kitty --class kittypad -e rmpc")
--	hl.exec_cmd("[workspace 1 silent] kitty -e nvim ")
--	hl.exec_cmd("[workspace 2 silent] kitty")
--	hl.exec_cmd("[workspace 3 silent] helium-browser")
	hl.exec_cmd("[workspace 10 silent] kitty --class kittypad -e rmpc")
end)
