cursor            #c2c6d6
cursor_text_color #2b303c

foreground #c8c6c7
background            #0e0e0f
selection_foreground  #2e3038
selection_background  #c4c6d0
url_color             #c4c6d0

# black / gray
color0  #0e0e0f
color8  #2a2a2b

# red
color1  #ffb4ab
color9  #93000a

# green (use primary instead of weird fixed)
color2  #c2c6d6
color10 #424753

# yellow (tertiary but stronger)
color3  #bfc6dc
color11 #3f4759

# blue (keep primary variant for clarity)
color4  #dee2f2
color12 #dee2f2

# magenta (secondary works better here)
color5  #c4c6d0
color13 #44474f

# cyan (use tertiary variant)
color6  #bfc6dc
color14 #dbe2f9

# white
color7  #e4e2e3
color15 #c8c6c7

mark1_foreground #161c27
mark1_background #dee2f2
mark2_foreground #191b22
mark2_background #e1e2ec
mark3_foreground #141b2c
mark3_background #dbe2f9

active_tab_foreground #2b303c
active_tab_background #c2c6d6
inactive_tab_foreground #dee2f2
inactive_tab_background #424753

active_border_color #c2c6d6
inactive_border_color #2b303c
# bell_border_color #ff5a00
